_target_: models.encoder.multiview_stack.MultiviewStack

encoders:
  - _target_: torch.load
    f: /nas/kathy/dynamo-weights/sim_kitchen_pretrained_model.pt # set the path to the encoder snapshot here
    weights_only: false
normalizations:
  - - [0, 0, 0]
    - [1, 1, 1]

output_dim: 512
